name: Pastebin CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build application
      run: dotnet publish --configuration release --output publish --runtime linux-x64 --self-contained
    - name: Bundle application
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r release.zip publish
    - name: Setup ssh
      uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        ORIGIN: ${{ secrets.SSH_HOST }}
        SSHKEY: ${{ secrets.SSH_KEY }}
        NAME: production
        PORT: ${{ secrets.SSH_PORT }}
        USER: ${{ secrets.SSH_USER }}
    - name: Deploy application
      run: cat release.zip | ssh production /root/deploy -c pastebin -i -