name: Pastebin CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: src/Pastebin.UI/client-app/package-lock.json
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - run: dotnet publish --configuration release --output publish --runtime linux-x64 --self-contained
